// Generated by https://quicktype.io

export interface ModernHouserResponse {
    A: House[];
    C: House[];
    D: House[];
    E: House[];
    G: House[];
    L: House[];
    M: House[];
    R: House[];
    S: House[];
    Z: House[];
}

export interface House {
    number:              string;
    id:                  number;
    name:                string;
    address:             string;
    description:         null | string;
    building_start_date: string;
    building_end_date:   string;
    name_translations:   NameTranslations;
    url:                 string;
    states_name:         StatesName;
    location:            Location;
    city_name:           CityName;
    city_longitude:      string;
    city_latitude:       string;
}

export enum CityName {
    SANFrancisco = "San Francisco",
}

export interface Location {
    latitude:  string;
    longitude: string;
}

export interface NameTranslations {
    es: string;
    en: string;
}

export enum StatesName {
    California = "California",
}
